saltandpepper_App/urls.py
from django.urls import path
from . import views
app_name = 'saltandpepper_App'
urlpatterns=[
    path('',views.index,name='index'),

    path('pizza',views.pizza,name='pizza'),
    path('burger',views.burger,name='burger'),
    path('order',views.order,name='order'),
    path('success',views.success,name='success'),
]

saltandpepper_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from saltandpepper_App import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('saltandpepper_App.urls',namespace='food'))
]

saltandpepper_App/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    name    =   models.CharField(max_length=100)
    priceM   =   models.DecimalField(max_digits=5,decimal_places=2)
    priceL   =   models.DecimalField(max_digits=5,decimal_places=2)
    pImage   =   models.URLField()

class Burger(models.Model):
    name    =   models.CharField(max_length=100)
    priceM   =   models.DecimalField(max_digits=5,decimal_places=2)
    priceL   =   models.DecimalField(max_digits=5,decimal_places=2)
    bImage   =   models.URLField()

saltandpepper_App/views.py
from django.http import HttpResponse
from django.shortcuts import render

from django.http import JsonResponse
# Create your views here.
from .models import Pizza, Burger
from django.views.decorators.csrf  import  csrf_exempt

def index(request):
    request.session.set_expiry(0)


    ctx={'active_link':'index'}
    return render(request,'food/index.html',ctx)
def pizza(request):
    request.session.set_expiry(0)

    pizzas=Pizza.objects.all()
    ctx={'pizza':pizzas,'active_link':'pizza'}
    return render(request,'food/pizza.html',ctx)
def burger(request):
    request.session.set_expiry(0)

    burgers=Burger.objects.all()
    ctx={'burger':burgers,'active_link':'burger'}
    return render(request,'food/burger.html',ctx)





@csrf_exempt
def order(request):
    request.session.set_expiry(0)
    if request.method=='POST':
        request.session['note'] = request.POST.get('note')
        print(request.session['note'])
        request.session['order'] = request.POST.get('orders')
        print(order)
    ctx={'active_link':'order'}
    return render(request,'food/order.html',ctx)

def success(request):
    order=request.session['order']
    ctx={'order':order}
    return render(request,'food/success.html',ctx)

templates/food/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'food/css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
  <a class="navbar-brand  " href="{% url 'food:index' %}">
    <img src="{% static 'food/images/logo.png' %}" alt="logo" style="width:40px;border-radius: 80px;" class="logo">
  </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynav" aria-controls="mynav"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="mynav">

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link {% if active_link == 'index' %}active{% endif %}" href="{% url 'food:index' %}">HOME</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if active_link == 'pizza' %}active{% endif %}" href="{% url 'food:pizza' %}">PIZZA</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if active_link == 'burger' %}active{% endif %}" href="{% url 'food:burger' %}">BURGUR</a>
    </li>
  </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item "><a class="nav-link {% if active_link == 'order' %}active{% endif %}" href="{% url 'food:order' %}" class="nav-link"><img src="{% static 'food/images/carticon.png' %}" style="width:30px;height: 30px;"><span id="cart">
              0 </span></a></li>
        <li class="nav-item"><a href="" class="nav-link"><img src="{% static 'food/images/iconuser.png' %}" style="width:30px;height: 30px;">LogIn</a></li>
  </ul>
</div>
</nav>

{% block content %}

{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>


<!-- jQuery library -->

<!-- Popper JS -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'food/js/main.js' %}"></script>


</body>
</html>

templates/food/burger.html
{% extends 'food/base.html' %}
{% load static %}

{% block title %}Pizza Round {% endblock %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 text-center">
            <h2 class="title">Burger Tower - Our Special Burger</h2>

            <div class="row">
            {% for i in burger %}
                <div class="col-md-6 p-2">
    <img class="picture" src="{{i.bImage}}">
                    <h6 class="pt-3" id="bur{{i.id}}">{{i.name}}</h6>
<!--                    Mediaum Price :₹,Large Price : ₹</h6>-->
                    <div class="form-check-inline">
                        <label class="form-check-label">
                            <input class="form-check-input" type="radio" name="burger{{i.id}}" value="{{i.priceM}}" checked>
                            M: {{i.priceM}}₹
                        </label>
                    </div>
                    <div class="form-check-inline">
                         <label class="form-check-label">
                             <input class="form-check-input" type="radio" name="burger{{i.id}}" value="{{i.priceL}}" >
                             L: {{i.priceL}}₹


                        </label>
                    </div>
                    <div >
                    <button class="btn-info m-3" onclick="addBurger('{{i.id}}')">Add to Cart</button></div>

</div>
{% endfor %}
        </div></div>
        <div class="col-md-4 orders">
            <div class="bg-dark text-white p-4">
            <h2 class="text-center">Order List</h2>
                        <ul id="bcart"></ul>

            <h6 class="text-right" id="btotal">Total : 0 ₹</h6>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'food/js/borders.js' %}"></script>

{% endblock %}

templates/food/index.html
{% extends 'food/base.html' %}


{% block title %}Salt And Pepper {% endblock %}
{% block content %}
<div class="home">

</div>
<h4>Salt And Pepper -Foodies Destiny</h4>
{% endblock %}

templates/food/order.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}Order Food here {% endblock %}
{% block content %}

<div class="container-fluid m-4">
    <div class="row">
    <div class="col-md-6 text-center">
        <h3>Order</h3>
        <div class="row">
            <div class="col-md-6" id="name">
                <h5>Name</h5>
            </div>
            <div class="col-md-1" id="size">
                <h5>Size</h5>
            </div>
            <div class="col-md-2" id="price">
                <h5>Price</h5>
            </div>
        </div>
        <h5 id="total">Total :</h5>
    </div>
        <div class="col-md-1" id="rm">

        </div>
    <div class="col-md-5 mt-4">
        <h5>Messages</h5>
        <textarea name="message" id="message" cols="40" rows="5"></textarea>
        <div class="ml-auto m-4">
        <button type="submit" class="btn-success" onclick="order()">submit</button>
            </div>
    </div>
    </div>
</div>

<script src="{% static 'food/js/cart.js' %}"></script>

{% endblock %}

templates/food/pizza.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}Pizza Round {% endblock %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 text-center">
            <h2 class="title">Pizza Rounds - Our Special Pizza</h2>

            <div class="row">
            {% for i in pizza %}
                <div class="col-md-6 p-2">
    <img class="picture" src="{{i.pImage}}">
                    <h6 class="pt-3" id="piz{{i.id}}">{{i.name}}</h6>
<!--                    Mediaum Price :₹,Large Price : ₹</h6>-->
                    <div class="form-check-inline">
                        <label class="form-check-label">
                            <input class="form-check-input" type="radio"  name="pizza{{i.id}}" value="{{i.priceM}}" checked>
                            M: {{i.priceM}}₹
                        </label>
                        
                    </div>
                    <div class="form-check-inline">
                         <label class="form-check-label">
                             <input class="form-check-input" type="radio" name="pizza{{i.id}}" value="{{i.priceL}}">
                             L: {{i.priceL}}₹


                        </label>
                    </div>
                    <div >
                    <button class="btn-info m-3" onclick="addPizza('{{i.id}}')">Add to Cart</button></div>

</div>
{% endfor %}
        </div></div>
        <div class="col-md-4 orders">
            <div class="bg-dark text-white p-4">
            <h2 class="text-center">Order List</h2>
            <ul id="pcart"></ul>
            <h6 class="text-right" id="ptotal">Total : 0 ₹</h6>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'food/js/order.js' %}"></script>

{% endblock %}

templates/food/success.html
{% extends 'food/base.html' %}
{% load static %}
{% block title %}Order Food here {% endblock %}
{% block content %}
  <div class="container-fluid">
    <h6>We have recived order</h6>
    <h4>{{order}}</h4>
  </div>

{% endblock %}